# Generated by Django 6.0.6 on 2026-07-17 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_role'),
    ]

    operations = [
    ]
