# Generated by Django 6.0.6 on 2026-07-23 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20260717_1811'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='otpverification',
            index=models.Index(fields=['user', 'purpose', 'is_verified'], name='OTP_Verific_user_id_7fbb86_idx'),
        ),
    ]
