# Generated by Django 6.0.6 on 2026-07-28 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_otpverification_otp_verific_user_id_7fbb86_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_premium',
            field=models.BooleanField(default=False),
        ),
    ]
