# Generated by Django 6.0.6 on 2026-07-28 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_add_has_premium_to_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCredit',
            fields=[
                ('credit_id', models.AutoField(primary_key=True, serialize=False)),
                ('quiz_used', models.IntegerField(default=0)),
                ('quiz_limit', models.IntegerField(default=20)),
                ('quiz_last_reset', models.DateField(blank=True, null=True)),
                ('coding_used', models.IntegerField(default=0)),
                ('coding_limit', models.IntegerField(default=20)),
                ('coding_last_reset', models.DateField(blank=True, null=True)),
                ('resume_used', models.IntegerField(default=0)),
                ('resume_limit', models.IntegerField(default=5)),
                ('resume_last_reset', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='credits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'User_Credits',
            },
        ),
    ]
