# Generated by Django 6.0.6 on 2026-08-09 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_usercredit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
    ]
