# Generated by Django 6.0.6 on 2026-07-25 01:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=50)),
                ('source_code', models.TextField()),
                ('stdin', models.TextField(blank=True, default='')),
                ('stdout', models.TextField(blank=True, default='')),
                ('stderr', models.TextField(blank=True, default='')),
                ('execution_status', models.CharField(choices=[('success', 'Success'), ('compile_error', 'Compilation Error'), ('runtime_error', 'Runtime Error'), ('timeout', 'Time Limit Exceeded'), ('error', 'Error')], default='success', max_length=30)),
                ('execution_time', models.FloatField(default=0.0, help_text='Execution time in seconds')),
                ('memory_used', models.IntegerField(blank=True, help_text='Memory used in KB', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='execution_histories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Execution Histories',
                'ordering': ['-created_at'],
            },
        ),
    ]
