# Generated by Django 6.0.6 on 2026-08-10 12:47

import course.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidate', '0004_candidate_profile_target_domain'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Course',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('domain_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Course_Domain',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('technology_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Technologies',
                'db_table': 'Course_Technology',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CourseModule',
            fields=[
                ('module_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='course.course')),
            ],
            options={
                'db_table': 'Course_Module',
                'ordering': ['sequence', 'module_id'],
            },
        ),
        migrations.CreateModel(
            name='CourseTopic',
            fields=[
                ('topic_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='course.coursemodule')),
            ],
            options={
                'db_table': 'Course_Topic',
                'ordering': ['sequence', 'topic_id'],
            },
        ),
        migrations.CreateModel(
            name='CourseMaterial',
            fields=[
                ('material_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='course_materials/%Y/%m/', validators=[course.validators.validate_pdf_file])),
                ('material_type', models.CharField(choices=[('PDF', 'PDF'), ('VIDEO', 'Video'), ('EXTERNAL_LINK', 'External Link')], default='PDF', max_length=20)),
                ('external_url', models.URLField(blank=True, max_length=500, null=True)),
                ('file_size', models.PositiveIntegerField(default=0, help_text='File size in bytes')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='course.coursetopic')),
            ],
            options={
                'db_table': 'Course_Material',
                'ordering': ['material_id'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='technology',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='course.technology'),
        ),
        migrations.CreateModel(
            name='CourseProgress',
            fields=[
                ('progress_id', models.AutoField(primary_key=True, serialize=False)),
                ('progress_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_accessed_at', models.DateTimeField(auto_now=True)),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_progresses', to='candidate.candidate_profile')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_progresses', to='course.course')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_progresses', to='course.domain')),
            ],
            options={
                'db_table': 'Course_Progress',
                'ordering': ['-last_accessed_at'],
                'unique_together': {('candidate', 'domain', 'course')},
            },
        ),
        migrations.CreateModel(
            name='CandidateTopicProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=True)),
                ('completed_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_progresses', to='candidate.candidate_profile')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_progresses', to='course.coursetopic')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_progresses', to='course.domain')),
            ],
            options={
                'db_table': 'Candidate_Topic_Progress',
                'unique_together': {('candidate', 'domain', 'topic')},
            },
        ),
        migrations.CreateModel(
            name='DomainCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('is_required', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_domains', to='course.course')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domain_courses', to='course.domain')),
            ],
            options={
                'db_table': 'Domain_Course',
                'ordering': ['sequence', 'id'],
                'unique_together': {('domain', 'course')},
            },
        ),
    ]
