# Generated by Django 6.0.6 on 2026-08-11 14:01

import course.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseprogress',
            name='completed_topic_ids',
        ),
        migrations.AddField(
            model_name='coursemodule',
            name='file_size',
            field=models.PositiveIntegerField(default=0, help_text='File size in bytes'),
        ),
        migrations.AddField(
            model_name='coursemodule',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='course_materials/%Y/%m/', validators=[course.validators.validate_pdf_file]),
        ),
        migrations.AddField(
            model_name='coursemodule',
            name='pdf_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='courseprogress',
            name='completed_module_ids',
            field=models.JSONField(blank=True, default=list, help_text='List of completed module IDs for this course'),
        ),
        migrations.DeleteModel(
            name='CourseTopic',
        ),
    ]
