# Generated by Django 6.0.6 on 2026-08-12 14:32

import course.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_remove_courseprogress_completed_topic_ids_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseMaterial',
            fields=[
                ('material_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('pdf_file', models.FileField(upload_to='course_materials/%Y/%m/', validators=[course.validators.validate_pdf_file])),
                ('file_size', models.PositiveIntegerField(default=0, help_text='File size in bytes')),
                ('extracted_text', models.TextField(blank=True, help_text='Cached text extracted from PDF', null=True)),
                ('text_extracted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='course.coursemodule')),
            ],
            options={
                'db_table': 'Course_Material',
                'ordering': ['material_id'],
            },
        ),
    ]
