# Generated by Django 6.0.6 on 2026-08-13 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_coursematerial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemodule',
            name='extracted_text',
            field=models.TextField(blank=True, help_text='Cached text extracted from PDF', null=True),
        ),
        migrations.AddField(
            model_name='coursemodule',
            name='text_extracted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
