# Generated by Django 6.0.6 on 2026-08-18 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_coursemodule_extracted_text_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseProgress',
        ),
    ]
