# Generated by Django 6.0.6 on 2026-08-09 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0003_alter_candidate_profile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate_profile',
            name='target_domain',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
