# Generated by Django 6.0.6 on 2026-08-10 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0004_candidate_profile_target_domain'),
        ('course', '__first__'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate_profile',
            name='active_domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidates', to='course.domain'),
        ),
    ]
