# Generated by Django 6.0.6 on 2026-08-01 03:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='quizperformance',
            index=models.Index(fields=['user', '-created_at'], name='quiz_quizpe_user_id_6d5b9b_idx'),
        ),
        migrations.AddIndex(
            model_name='quizperformance',
            index=models.Index(fields=['user', 'score'], name='quiz_quizpe_user_id_b7e1f1_idx'),
        ),
    ]
