# Generated by Django 6.0.6 on 2026-08-12 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0005_candidate_profile_active_domain'),
        ('course', '0003_coursematerial'),
        ('quiz', '0002_quizperformance_quiz_quizpe_user_id_6d5b9b_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChapterQuiz',
            fields=[
                ('quiz_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('difficulty', models.CharField(default='Medium', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chapter_quizzes', to='candidate.candidate_profile')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapter_quizzes', to='course.course')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapter_quizzes', to='course.coursemodule')),
            ],
            options={
                'db_table': 'Quiz_ChapterQuiz',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChapterQuestion',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('question_text', models.TextField()),
                ('option_a', models.TextField()),
                ('option_b', models.TextField()),
                ('option_c', models.TextField()),
                ('option_d', models.TextField()),
                ('correct_answer', models.CharField(max_length=200)),
                ('explanation', models.TextField(blank=True, null=True)),
                ('source_material_name', models.CharField(blank=True, max_length=250, null=True)),
                ('source_topic', models.CharField(blank=True, max_length=250, null=True)),
                ('source_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='course.coursematerial')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quiz.chapterquiz')),
            ],
            options={
                'db_table': 'Quiz_ChapterQuestion',
                'ordering': ['question_id'],
            },
        ),
    ]
