# Generated by Django 6.0.6 on 2026-08-13 02:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_coursemodule_extracted_text_and_more'),
        ('quiz', '0003_chapterquiz_chapterquestion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quizperformance',
            name='domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quiz_performances', to='course.domain'),
        ),
        migrations.AddIndex(
            model_name='quizperformance',
            index=models.Index(fields=['user', 'domain', '-created_at'], name='quiz_quizpe_user_id_72c501_idx'),
        ),
    ]
