# Generated by Django 6.0.6 on 2026-07-22 02:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interviewer_Profile',
            fields=[
                ('interviewer_id', models.AutoField(primary_key=True, serialize=False)),
                ('profile_picture', models.ImageField(blank=True, default='interviewer_pics/default.jpg', upload_to='interviewer_pics/')),
                ('department', models.CharField(blank=True, max_length=150, null=True)),
                ('designation', models.CharField(blank=True, max_length=150, null=True)),
                ('expertise_area', models.TextField(blank=True, null=True)),
                ('years_of_experience', models.DecimalField(decimal_places=1, default=0.0, max_digits=4)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Interviewer_Profile',
            },
        ),
        migrations.CreateModel(
            name='InterviewerAvailability',
            fields=[
                ('availability_id', models.AutoField(primary_key=True, serialize=False)),
                ('day_of_week', models.SmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.CharField(choices=[('available', 'Available'), ('booked', 'Booked'), ('unavailable', 'Unavailable')], default='available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='interviewer.interviewer_profile')),
            ],
            options={
                'db_table': 'Interviewer_Availability',
                'indexes': [models.Index(fields=['interviewer', 'day_of_week', 'start_time'], name='Interviewer_intervi_f14f96_idx')],
            },
        ),
    ]
