# Generated by Django 6.0.6 on 2026-07-28 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviewer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewer_profile',
            name='company',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='interviewer_profile',
            name='github_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='interviewer_profile',
            name='linkedin_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='interviewer_profile',
            name='website_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
