# Generated by Django 6.0.6 on 2026-07-17 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviewer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewer_profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='interviewer_profile',
            name='linkedin_url',
        ),
        migrations.RemoveField(
            model_name='interviewer_profile',
            name='organization',
        ),
        migrations.AlterField(
            model_name='interviewer_profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='interviewer_pics/default.jpg', upload_to='interviewer_pics/'),
        ),
    ]
