# Generated by Django 6.0.6 on 2026-07-21 01:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviewer', '0002_remove_interviewer_profile_bio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewerAvailability',
            fields=[
                ('availability_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('available', 'Available'), ('booked', 'Booked'), ('unavailable', 'Unavailable')], default='available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='interviewer.interviewer_profile')),
            ],
            options={
                'db_table': 'Interviewer_Availability',
                'indexes': [models.Index(fields=['interviewer', 'start_time'], name='Interviewer_intervi_e59e5b_idx')],
            },
        ),
    ]
