# Generated by Django 6.0.6 on 2026-07-13 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('resume_id', models.AutoField(primary_key=True, serialize=False)),
                ('candidate_id', models.IntegerField()),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=500)),
                ('file_size_kb', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('analyzed', 'Analyzed'), ('failed', 'Failed')], default='uploaded', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Resume',
            },
        ),
        migrations.CreateModel(
            name='ResumeAnalysis',
            fields=[
                ('analysis_id', models.AutoField(primary_key=True, serialize=False)),
                ('summary', models.TextField(blank=True, null=True)),
                ('resume_score', models.IntegerField(blank=True, null=True)),
                ('role', models.CharField(blank=True, max_length=150, null=True)),
                ('experience', models.TextField(blank=True, null=True)),
                ('extracted_skills', models.TextField(blank=True, null=True)),
                ('matched_skills', models.TextField(blank=True, null=True)),
                ('missing_skills', models.TextField(blank=True, null=True)),
                ('suggested_next_skills', models.TextField(blank=True, null=True)),
                ('skill_category', models.TextField(blank=True, null=True)),
                ('suggestion_1', models.TextField(blank=True, null=True)),
                ('suggestion_2', models.TextField(blank=True, null=True)),
                ('suggestion_3', models.TextField(blank=True, null=True)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('resume', models.OneToOneField(db_column='resume_id', on_delete=django.db.models.deletion.CASCADE, to='resume.resume')),
            ],
            options={
                'db_table': 'Resume_Analysis',
            },
        ),
    ]
