# Generated by Django 6.0.6 on 2026-07-12 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeAnalysis',
            fields=[
                ('analysis_id', models.AutoField(primary_key=True, serialize=False)),
                ('extracted_skills', models.TextField(blank=True, null=True)),
                ('resume_score', models.IntegerField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('suggestions', models.TextField(blank=True, null=True)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('resume', models.OneToOneField(db_column='resume_id', on_delete=django.db.models.deletion.CASCADE, to='resume.resume')),
            ],
            options={
                'db_table': 'Resume_Analysis',
            },
        ),
    ]
