# Generated by Django 6.0.6 on 2026-07-17 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_resumeanalysis'),
        ('resume', '0002_resumeanalysis_candidate_name_and_more'),
    ]

    operations = [
    ]
