# Generated by Django 6.0.6 on 2026-07-18 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_merge_20260717_1805'),
        ('resume', '0004_remove_resumeanalysis_suggestions_and_more'),
    ]

    operations = [
    ]
