# Generated by Django 6.0.6 on 2026-08-09 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_merge_20260718_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='domain_match_feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='domain_match_score',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='domain_match_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='target_domain',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
