# Generated by Django 6.0.6 on 2026-07-18 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidate', '0003_alter_candidate_profile_profile_picture'),
        ('interviewer', '0002_remove_interviewer_profile_bio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewSchedule',
            fields=[
                ('schedule_id', models.AutoField(primary_key=True, serialize=False)),
                ('scheduled_date', models.DateField()),
                ('scheduled_time', models.TimeField()),
                ('duration_minutes', models.IntegerField()),
                ('status', models.CharField(max_length=11)),
                ('meeting_link', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('room_name', models.CharField(blank=True, max_length=255, null=True)),
                ('candidate', models.ForeignKey(db_column='candidate_id', on_delete=django.db.models.deletion.DO_NOTHING, to='candidate.candidate_profile')),
                ('interviewer', models.ForeignKey(db_column='interviewer_id', on_delete=django.db.models.deletion.DO_NOTHING, to='interviewer.interviewer_profile')),
            ],
            options={
                'db_table': 'Interview_Schedule',
                'managed': True,
            },
        ),
    ]
