# Generated by Django 6.0.6 on 2026-07-18 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interviewschedule',
            options={'managed': False},
        ),
    ]
