# Generated by Django 6.0.6 on 2026-07-24 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0003_alter_candidate_profile_profile_picture'),
        ('interview', '0002_allow_pending_status'),
        ('interviewer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewFeedbackReview',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('technical_skills', models.IntegerField(default=3)),
                ('communication_skills', models.IntegerField(default=3)),
                ('problem_solving', models.IntegerField(default=3)),
                ('soft_skills', models.IntegerField(default=3)),
                ('code_quality', models.IntegerField(default=3)),
                ('overall_rating', models.DecimalField(decimal_places=1, default=3.0, max_digits=3)),
                ('strengths', models.TextField(blank=True, null=True)),
                ('weaknesses', models.TextField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('recommendation', models.CharField(choices=[('Strongly Recommend', 'Strongly Recommend'), ('Recommend', 'Recommend'), ('Neutral', 'Neutral'), ('Do Not Recommend', 'Do Not Recommend')], default='Recommend', max_length=30)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(db_column='candidate_id', on_delete=django.db.models.deletion.CASCADE, related_name='feedback_reviews', to='candidate.candidate_profile')),
                ('interviewer', models.ForeignKey(db_column='interviewer_id', on_delete=django.db.models.deletion.CASCADE, related_name='given_feedback_reviews', to='interviewer.interviewer_profile')),
                ('schedule', models.ForeignKey(blank=True, db_column='schedule_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_reviews', to='interview.interviewschedule')),
            ],
            options={
                'db_table': 'Interview_Feedback_Review',
            },
        ),
    ]
