# Generated by Django 6.0.6 on 2026-07-18 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0002_alter_interviewschedule_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interviewschedule',
            options={},
        ),
    ]
