# Generated by Django 6.0.6 on 2026-07-18 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0003_alter_interviewschedule_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interviewschedule',
            options={'managed': False},
        ),
    ]
