# Generated by Django 6.0.6 on 2026-08-02 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0003_interviewfeedbackreview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewfeedbackreview',
            name='code_quality',
        ),
    ]
