# Generated by Django 6.0.6 on 2026-08-13 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_coursemodule_extracted_text_and_more'),
        ('interview', '0004_remove_interviewfeedbackreview_code_quality'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewfeedbackreview',
            name='domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_reviews', to='course.domain'),
        ),
    ]
