# Generated by Django 6.0.6 on 2026-07-23 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='codesubmission',
            name='input_data',
            field=models.TextField(blank=True),
        ),
    ]
