# Generated by Django 6.0.6 on 2026-08-01 03:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0003_codesubmission_ai_evaluation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='codesubmission',
            options={'ordering': ['-submitted_at']},
        ),
        migrations.AddIndex(
            model_name='codesubmission',
            index=models.Index(fields=['user', '-submitted_at'], name='coding_code_user_id_2063b0_idx'),
        ),
        migrations.AddIndex(
            model_name='codesubmission',
            index=models.Index(fields=['user', 'score'], name='coding_code_user_id_acad1a_idx'),
        ),
    ]
