# Generated by Django 6.0.6 on 2026-08-13 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0004_alter_codesubmission_options_and_more'),
        ('course', '0004_coursemodule_extracted_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='codesubmission',
            name='domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='code_submissions', to='course.domain'),
        ),
    ]
