# Generated by Django 6.0.6 on 2026-07-16 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('overall_experience', models.CharField(choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Average', 'Average'), ('Poor', 'Poor')], max_length=20)),
                ('resume_manager', models.TextField()),
                ('mock_interview', models.TextField()),
                ('coding_assessment', models.CharField(choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Average', 'Average'), ('Poor', 'Poor')], max_length=20)),
                ('aptitude_test', models.CharField(choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Average', 'Average'), ('Poor', 'Poor')], max_length=20)),
                ('dashboard_experience', models.CharField(choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Average', 'Average'), ('Poor', 'Poor')], max_length=20)),
                ('suggestions', models.TextField(blank=True)),
                ('comments', models.TextField(blank=True)),
                ('recommend', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'feedback',
            },
        ),
    ]
