# Generated by Django 6.0.6 on 2026-07-16 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='dashboard_experience',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='resume_manager',
        ),
        migrations.AddField(
            model_name='feedback',
            name='recommendation_reason',
            field=models.TextField(blank=True),
        ),
    ]
