# Generated by Django 6.0.6 on 2026-07-18 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_remove_feedback_dashboard_experience_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='aptitude_test',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='coding_assessment',
        ),
    ]
